export class User {
  constructor(
    public readonly id: string,
    public username: string,
    public email: string,
    public passwordHash: string,
    public avatarUrl: string | null,
    public level: number,
    public readonly createdAt: Date,
    public updatedAt: Date,
  ) {}

  static create(
    username: string,
    email: string,
    passwordHash: string,
  ): User {
    const now = new Date();
    return new User(
      '', // ID will be generated by database
      username,
      email,
      passwordHash,
      null,
      1,
      now,
      now,
    );
  }

  updateProfile(username?: string, avatarUrl?: string): void {
    if (username) this.username = username;
    if (avatarUrl !== undefined) this.avatarUrl = avatarUrl;
    this.updatedAt = new Date();
  }

  validatePassword(passwordHash: string): boolean {
    return this.passwordHash === passwordHash;
  }
}